-- MySQL Script generated by MySQL Workbench
-- Sat Oct 24 13:55:01 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Musica` (
  `idMusica` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NomeMusica` VARCHAR(45) NOT NULL COMMENT '',
  `NomeAlbum` VARCHAR(45) NULL COMMENT '',
  `NomeArtista` VARCHAR(45) NULL COMMENT '',
  `Genero` VARCHAR(45) NOT NULL COMMENT '',
  `Class` INT NULL COMMENT '',
  PRIMARY KEY (`idMusica`)  COMMENT '',
  UNIQUE INDEX `idMusica_UNIQUE` (`idMusica` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
